"""Measure the anchors off the rendered art and emit the Kotlin manifest.

The numbers are read from each fill layer's alpha bounding box rather than copied
out of the drawing code, so moving a tank in `machines.py` moves the anchors with
it. Run after `slurry.py` / `machines.py`.
"""
import glob
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from kit import OUT, W, H  # noqa


def bbox(png):
    """Alpha bounding box of the fill layer, as (x, y, w, h) in image pixels."""
    out = subprocess.run(["magick", png, "-trim", "-format", "%w %h %X %Y", "info:"],
                         capture_output=True, text=True, check=True).stdout.split()
    w, h, x, y = int(out[0]), int(out[1]), int(out[2].lstrip("+")), int(out[3].lstrip("+"))
    return x, y, w, h


def main():
    rows = []
    for png in sorted(glob.glob(os.path.join(OUT, "*_fill.png"))):
        name = os.path.basename(png)[: -len("_fill.png")]
        x, y, w, h = bbox(png)
        rows.append(dict(
            name=name,
            top=y / H,
            bottom=(y + h) / H,
            cx=(x + w / 2) / W,
            cy=(y + h / 2) / H,
        ))

    lines = [
        "// Generated by tools/isobus-art/manifest.py — do not hand-edit.",
        "// Fractions of the 1600x1000 canvas, measured off the fill layers' alpha bounds.",
        "",
        "data class MachineArt(",
        "    val body: DrawableResource,",
        "    val fill: DrawableResource? = null,",
        "    /** y fraction the fill reaches at 100%, so a part-full tank clips to the tank. */",
        "    val fillClipTop: Float = 0f,",
        "    /** y fraction of the tank floor — the other end of that clip. */",
        "    val fillClipBottom: Float = 0f,",
        "    /** where the boxed level figure sits, on the body. */",
        "    val readoutAt: Offset = Offset.Unspecified,",
        ")",
        "",
    ]
    for r in rows:
        lines += [
            f"val {r['name'].replace('isobus_', '').upper()} = MachineArt(",
            f"    body = Res.drawable.{r['name']}_body,",
            f"    fill = Res.drawable.{r['name']}_fill,",
            f"    fillClipTop = {r['top']:.3f}f,",
            f"    fillClipBottom = {r['bottom']:.3f}f,",
            f"    readoutAt = Offset({r['cx']:.3f}f, {r['cy']:.3f}f),",
            ")",
        ]

    text = "\n".join(lines) + "\n"
    path = os.path.join(OUT, "MachineArt.kt.snippet")
    with open(path, "w") as f:
        f.write(text)
    print(text)
    print("wrote", path)


if __name__ == "__main__":
    main()
