-- Model definitions for the fleet export channel (fleet.json, src/collect/FleetExporter.lua).
--
-- Annotation-only (LuaLS @class): these files carry NO runtime logic and are not source()'d.
-- The shape maps 1:1 to the Kotlin model in VDTerminal/shared (model/Fleet.kt) and the fixtures in
-- examples/json/fleet/*.
--
-- One entry per MACHINE, not per rig: the game's own vehicle overview lists an implement on its own
-- row, and so do we (`attachedTo` says which rig it is currently part of). posX/posZ are normalized
-- [0,1] map coordinates in the same frame as MapModel / MapVehicleModel, so the app can hand a row
-- straight to the map.

-- The Advanced Damage System block of one fleet row: whether the machine is in ADS's workshop, and
-- where it is in its service interval. Present only for machines ADS manages (motorized, not
-- excluded). Deliberately this small since ADS 0.9.9.3 -- see src/integrations/AdvancedDamageSystem.lua.
--
-- `service` is the SAME shape the driven vehicle's `ads` block uses.
---@class FleetAdsModel
---@field state string READY | INSPECTION | MAINTENANCE | REPAIR | BROKEN | UNKNOWN
---@field service AdsServiceModel?

-- One machine of the farm's fleet.
--
-- CONDITION: `wearable.damage` is the vanilla figure and is pinned to 0 on any machine ADS manages,
-- so a reader takes condition from `wearable` only where the ads block is ABSENT; an ADS machine has
-- no condition on the wire at all (see Fleet.kt, which says the same thing to the app).
---@class FleetVehicleModel
---@field id number network object id (NOT uniqueId -- nil on a multiplayer client)
---@field name string
---@field type string VehicleHotspot.TYPE key, camelCased -- same tokens as MapVehicleModel.type
---@field category string? localized store category ("Tractors", "Ploughs", ...)
---@field age number age in months, as the game counts it
---@field hours number operating hours
---@field propertyState string OWNED | LEASED | MISSION
---@field sellPrice number? what the game would pay for it; owned machines only
---@field leasePerDay number? running + per-day leasing cost; leased machines only
---@field wearable WearableModel?
---@field fillUnits FillUnitsModel?
---@field motorFillUnits MotorFillUnitsModel? fuel/def/air; also marks the machine as motorized
---@field broken boolean? drowned and waiting for a reset; absent on a working machine
---@field attachedTo number? id of the rig's root vehicle, when this machine is attached to one
---@field isAI boolean? an AI helper is driving it
---@field isControlled boolean? a human is driving it (any player in MP)
---@field isEntered boolean? the LOCAL player is inside
---@field isTabbable boolean? in the tab rotation; absent for a machine with no seat. False is how a
---       park mod marks a machine as put away (Enterable:setIsTabbable)
---@field posX number?
---@field posZ number?
---@field ads FleetAdsModel?

---@class FleetModel
---@field version string
---@field vehicles FleetVehicleModel[]?
