-- Model definition for an implement node (recursive). Annotation-only (see EnvironmentModel.lua).
-- Maps to the Kotlin model's Implement (model/Vehicle.kt). `brand` is emitted (preserving current behaviour) but absent from
-- it, so the server drops it via ignoreUnknownKeys.

---@class ImplementModel
---@field position string
---@field name string?
---@field type string?
---@field brand BrandModel?
---@field isTurnedOn boolean?
---@field foldable string?
---@field lowered boolean?
---@field fillUnits FillUnitsModel?
---@field mass MassModel?
---@field pipe PipeModel?
---@field cover CoverModel?
---@field wearable WearableModel?
---@field schema SchemaModel?
---@field selection SelectionModel?
---@field discharge DischargeModel?
---@field tipping TippingModel?
---@field harvest HarvestModel?
---@field workMode WorkModeModel?
---@field workWidth WorkWidthModel?
---@field workAreas WorkAreaModel[]?
---@field baleCounter BaleCounterModel?
---@field sowing SowingModel?
---@field spraying SprayingModel?
---@field plow PlowModel?
---@field tillage TillageModel?
---@field mixer MixerModel?
---@field jointDescIndex number?
---@field implement ImplementModel[]?
