-- Model definitions for the steering subtree. Annotation-only (see EnvironmentModel.lua).
-- Maps to Model.kt Steering / SteeringMode.

--- The steering mode a crab-steering machine is in.
---
--- `name` is the game's own wording for it, straight out of the vehicle's XML and translated — the
--- only thing the game itself shows. `layout` is derived from the wheels instead (see
--- collect/vehicle/Steering.lua), because that name is free text a consumer cannot draw from.
---@class SteeringModeModel
---@field name string? absent when the vehicle's XML names no mode
---@field index number which mode of `count`, 1-based
---@field count number how many modes this machine has
--- `layout` is absent when the wheels can't be read that way. Its two crab values are not a
--- redundancy: a machine that crabs by steering its rear axle along with the front does it in
--- whichever direction the driver turns (CRAB), while one that crabs by parking that axle over has
--- the direction baked into the mode, and so offers two of them (CRAB_LEFT / CRAB_RIGHT).
---@field layout string? FRONT | BACK | ALL_WHEEL | CRAB | CRAB_LEFT | CRAB_RIGHT

--- How the machine is set up to be driven. Both halves are independent and either can be absent: a
--- telehandler has steering modes and no reversible seat, a Fendt the other way round, a Xerion both.
---@class SteeringModel
---@field mode SteeringModeModel? absent unless the vehicle has crab-steering modes
---@field reversed boolean? the driving position is turned round; absent unless the vehicle has one
---@field changing boolean? mid-swivel, while the seat animation runs
