-- Model definitions for the storage export channel (storage.json,
-- src/collect/StorageExporter.lua).
--
-- Annotation-only (LuaLS @class): these files carry NO runtime logic and are not source()'d.
-- The shape maps 1:1 to the Kotlin model in VDTerminal/shared (model/Storage.kt) and the fixtures in
-- examples/json/storage/*.
--
-- Scope: the LOCAL player's farm only (see g_localPlayer.farmId) — everything it holds outside a
-- production point: the standalone storage placeables (liter silos, manure heaps, object storages),
-- the silage
-- bunkers, and the loose bales and pallets lying around. Split off the sibling production channel
-- (src/model/ProductionModel.lua); the per-row ProductionFillModel is defined there and reused here
-- for a silo's fills (a silo's rows look exactly like a production point's internal storage rows).

---@class StoredObjectModel a group of identical stored objects in an object storage
---@field index number the group's objectInfoIndex (1-based) — the unload command's addressing key
---@field title string display name (the abstract object's dialog text, e.g. "Round bale (Straw)")
---@field count number number of that object currently stored
---@field kind string? what the objects ARE: "BALE" | "PALLET" | "BIGBAG" — the same vocabulary
---  LooseStockModel uses, so the two lists can be read as one
---@field shape string? "ROUND" | "SQUARE", on kind=="BALE" only
---@field type string? fill type name of what the objects HOLD — a separate question from `kind`, and
---  one that fails on its own: a crate or a vegetable pallet holds no fill type at all
---@field level number? liters in ONE of those objects — the group is identical objects, fill level
---  included, so the group holds level * count. Absent together with `type`.

---@class StoredObjectDetail what one stored object is, read off its abstract stand-in (internal)
---@field kind string "BALE" | "PALLET" | "BIGBAG"
---@field shape string? "ROUND" | "SQUARE" when it is a bale
---@field type string? fill type name, absent when the object holds none
---@field level number? liters in that one object, absent together with `type`

---@class StandaloneStorageModel an owned storage placeable with no production. A placeable a
---  husbandry has taken over as its own store — the manure heap behind the barn, an `isExtension`
---  slurry tank — is NOT one of these: those liters are reported by husbandry.json's condition bars,
---  which carry a fill type of their own, so that nothing counts them twice.
---@field id string stable id for app selection (placeable uniqueId, else a synthesized fallback)
---@field name string display name (owning placeable's name)
---@field kind string "fill" (liter silo) or "object" (object storage: bales/pallets, count-based)
---@field fills ProductionFillModel[]? kind=="fill": one row per stored fill type
---@field objects StoredObjectModel[]? kind=="object": per-type item counts (may be partial on MP clients)
---@field count number? kind=="object": total number of objects currently stored
---@field capacity number? kind=="object": maximum number of objects
---@field maxUnloadAmount number? kind=="object": per-action unload cap (the effective max per type is
---  min(this, that group's count))

---@class BunkerSiloModel a silage bunker (PlaceableBunkerSilo, or one bay of a multi-bay placeable)
---@field id string stable id (placeable uniqueId, else a synthesized fallback; bay number appended)
---@field name string display name (owning placeable's name, bay number appended when it has bays)
---@field state string "FILL" | "CLOSED" | "FERMENTED" | "DRAIN"
---@field type string? fill type name — the input type while filling, the output type once closed
---@field title string? localized fill type title
---@field level number liters currently in the bunker (there is no capacity: the walls are the limit)
---@field compacted number? compaction percent 0..100 — present in state "FILL" only
---@field fermenting number? fermentation percent 0..100 — present in "CLOSED"/"FERMENTED" only

---@class LooseStockModel bales or pallets lying around the farm, grouped by fill type and form
---@field type string fill type name
---@field title string localized fill type title
---@field kind string what they ARE: "BALE" | "PALLET" | "BIGBAG"
---@field shape string? "ROUND" | "SQUARE", on kind=="BALE" only
---@field count number how many objects are in the group
---@field level number liters the whole group holds (a TOTAL, unlike StoredObjectModel.level)
---@field fermenting number? bales only: how many of them are still fermenting, so still report the
---  fill type they went in as rather than what they will become

---@class StorageModel
---@field version string channel version, independent of VDTelemetry.VERSION
---@field storages StandaloneStorageModel[]?
---@field bunkerSilos BunkerSiloModel[]?
---@field looseBales LooseStockModel[]?
---@field loosePallets LooseStockModel[]?
