-- Model definitions for the vehicle subtree. Annotation-only (see EnvironmentModel.lua).
-- (`combined` aggregation is intentionally not emitted — deferred until a consumer needs it.)

---@class SpeedModel
---@field value number
---@field unit string?
---@field direction string? the way the machine is travelling; STOPPED below walking pace

---@class BrandModel
---@field name string?
---@field title string?

---@class OperatingTimeModel
---@field value string
---@field unit string

-- The isTurnedOn..wearable fields are the shared aspects (see collect/aspects/), identical to the
-- ones on ImplementModel.
---@class VehicleModel
---@field name string
---@field type string
---@field speed SpeedModel
---@field brand BrandModel?
---@field operatingTime OperatingTimeModel?
---@field motor MotorModel?
---@field lights LightsModel?
---@field steering SteeringModel?
---@field gps GpsModel?
---@field ai AiModel?
---@field cruiseControl CruiseControlModel?
---@field isTurnedOn boolean?
---@field foldable string?
---@field lowered boolean?
---@field fillUnits FillUnitsModel?
---@field pipe PipeModel?
---@field cover CoverModel?
---@field wearable WearableModel?
---@field schema SchemaModel?
---@field selection SelectionModel?
---@field discharge DischargeModel?
---@field tipping TippingModel?
---@field harvest HarvestModel?
---@field workMode WorkModeModel?
---@field workWidth WorkWidthModel?
---@field workAreas WorkAreaModel[]?
---@field baleCounter BaleCounterModel?
---@field sowing SowingModel?
---@field spraying SprayingModel?
---@field plow PlowModel?
---@field tillage TillageModel?
---@field implement ImplementModel[]?
